# Generated by Django 3.0.8 on 2020-08-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20200826_0016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusDriver',
            new_name='BtDriver',
        ),
    ]
