# Generated by Django 3.0.8 on 2020-08-28 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=10)),
                ('spend_time', models.DecimalField(decimal_places=1, max_digits=120)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('direction', models.CharField(max_length=100)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=100)),
                ('bus', models.CharField(max_length=100)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.Route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='stations',
            field=models.ManyToManyField(to='trips.Station'),
        ),
    ]
