# Generated by Django 3.0.8 on 2020-09-05 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200826_0016'),
        ('admins', '0003_auto_20200828_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.BtUser'),
        ),
    ]
