# Generated by Django 3.0.8 on 2020-08-10 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200810_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='btuser',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btuser',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='btuser',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
